/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
 // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
 
  tutorialSidebar: [
    'intro',
    'hello',
    'interestingPages',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document','tutorial-basics/demodoc'],
    },
    {
      type: 'category',
      label: 'Tutorial extra',
      items: ['tutorial-extras/manage-docs-versions'],
    },
    
  ],  
  
};
/*
tutorialsidebar: [
  {
    type: 'category',
    label: 'Tutorial',
    items: ['hello', 'intro'],
  },
  {
    type: 'category',
    label: 'Basics',
    items: ['tutorial-basics/create-a-document.md', 'intro'],
  },
]
*/
module.exports = sidebars;
